# Generated by Django 3.0.8 on 2020-07-31 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('version', models.CharField(max_length=80)),
                ('desc', models.TextField(blank=True, null=True)),
                ('repo_url', models.CharField(max_length=100)),
                ('build_status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('NOT_BUILT', 'Not Built'), ('BUILDING', 'Building')], default='NOT_BUILT', max_length=10)),
                ('build_date', models.DateTimeField(blank=True, null=True)),
                ('build_output', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
